const DATA = {
  name: "Jagan M",
  role: "Java Full Stack Developer",
  tagline: "Building scalable systems from DB to UI",
  bio: [
    "I'm an enthusiastic B.Tech graduate in Artificial Intelligence and Data Science from Anand Institute of Higher Technology, Chennai. With a CGPA of 7.61, I've built a strong foundation in both AI/ML concepts and full-stack web development.",
    "Completed an internship at Arul Technologies working on AI & IoT, authored a research paper published in IJCRT, and earned certifications from Oracle and MongoDB.",
    "Recently completed Java Full Stack Developer training at Qspiders (2026), mastering Core Java, JDBC, REST APIs, Spring Boot, and React.",
  ],
  objective:
    "To secure a challenging position as a Java Full Stack Developer where I can leverage my technical knowledge, problem-solving skills, and passion for technology to contribute meaningfully to real-world software projects.",
  contact: {
    email: "Jagan123464@gmail.com",
    phone: "+91 9791077762",
    linkedin: "linkedin.com/in/jagan-m",
    github: "github.com/Jagan123464",
    location: "Chennai, Tamil Nadu",
  },
  stats: [
    { val: "3+", lbl: "Projects" },
    { val: "7.61", lbl: "CGPA" },
    { val: "6+", lbl: "Certs" },
    { val: "1", lbl: "Publication" },
  ],
  skills: [
    {
      cat: "Frontend",
      icon: "🌐",
      color: "#3b7eff",
      glow: "rgba(59,126,255,0.25)",
      items: ["HTML5", "CSS3", "JavaScript", "React.js", "Figma", "Responsive Design"],
    },
    {
      cat: "Backend",
      icon: "⚙️",
      color: "#a78bfa",
      glow: "rgba(167,139,250,0.25)",
      items: ["Core Java", "OOP", "Collections", "JDBC", "REST APIs", "Spring Boot"],
    },
    {
      cat: "Database",
      icon: "🗄️",
      color: "#22d3ee",
      glow: "rgba(34,211,238,0.25)",
      items: ["MySQL", "SQL", "MongoDB", "JDBC Connectivity", "DB Design"],
    },
    {
      cat: "Tools & AI",
      icon: "🧠",
      color: "#f59e0b",
      glow: "rgba(245,158,11,0.25)",
      items: ["Git", "GitHub", "VS Code", "Eclipse", "Python", "Machine Learning", "NLP"],
    },
  ],
  projects: [
    {
      num: "01",
      cat: "DATA ANALYTICS",
      title: "Android Play Store Analysis",
      desc: "Comprehensive EDA and clustering analysis on Android Play Store dataset to uncover app market trends, user preferences, and performance patterns.",
      features: [
        "Exploratory Data Analysis on ratings, installs & reviews",
        "K-Means clustering to segment apps by key features",
        "Market trend insights for data-driven app strategy",
        "Visualization of distinct app performance clusters",
      ],
      stack: ["Python", "K-Means", "Pandas", "Matplotlib", "Scikit-learn"],
      gradient: "linear-gradient(135deg,#1a56db,#06b6d4)",
      icon: "📊",
    },
    {
      num: "02",
      cat: "AI · RESEARCH",
      title: "AI-Powered HR Recruitment System",
      desc: "Intelligent recruitment platform automating candidate sourcing, screening and ranking. Published in IJCRT (April 2025).",
      features: [
        "Automated resume screening using NLP techniques",
        "ML-based candidate ranking and shortlisting",
        "Predictive analytics on historical hiring data",
        "Bias reduction through data-driven decisions",
      ],
      stack: ["Python", "NLP", "Machine Learning", "Predictive Analytics"],
      gradient: "linear-gradient(135deg,#7c3aed,#3b7eff)",
      icon: "🤖",
    },
    {
      num: "03",
      cat: "FULL STACK",
      title: "Full Stack Web Application",
      desc: "Responsive, feature-rich web application built with Java backend and React frontend, demonstrating full-stack capabilities with REST API integration.",
      features: [
        "RESTful API design with Java backend logic",
        "React.js responsive and dynamic frontend",
        "MySQL database with JDBC connectivity",
        "CRUD operations and user authentication",
      ],
      stack: ["Java", "React.js", "MySQL", "REST API", "HTML/CSS"],
      gradient: "linear-gradient(135deg,#06b6d4,#f59e0b)",
      icon: "💻",
    },
  ],
  experience: [
    {
      role: "Artificial Intelligence & IoT Intern",
      org: "Arul Technologies, Chennai",
      date: "June 2023 – July 2023",
      desc: "Four-week intensive internship focused on real-time implementation of IoT and AI systems.",
      points: [
        "Developed IoT prototypes using Arduino, Blynk, and ThingSpeak platforms",
        "Implemented real-time data monitoring and AI-based control systems",
        "Enhanced skills in data analysis, IoT integration, and sensor-based programming",
        "Delivered functional prototypes demonstrating end-to-end IoT pipelines",
      ],
      color: "#3b7eff",
    },
    {
      role: "Java Full Stack Developer Training",
      org: "Qspiders, Chennai",
      date: "2025 – 2026",
      desc: "Comprehensive professional training program covering end-to-end Java full stack development.",
      points: [
        "Mastered Core Java, OOPS, Collections Framework, and JDBC",
        "Built responsive frontends using HTML, CSS, JavaScript, and React.js",
        "Designed and queried relational databases using MySQL",
        "Developed full-stack applications integrating backend with frontend UI",
      ],
      color: "#a78bfa",
    },
  ],
  education: [
    {
      degree: "B.Tech — AI & Data Science",
      inst: "Anand Institute of Higher Technology, Chennai",
      period: "2021 – 2025",
      score: "CGPA: 7.61 · First Class",
      icon: "🎓",
    },
    {
      degree: "Higher Secondary (12th)",
      inst: "State Board of School Examinations, TN",
      period: "May 2021",
      score: "61.03",
      icon: "🏫",
    },
    {
      degree: "Secondary (10th / SSLC)",
      inst: "State Board of School Examinations, TN",
      period: "May 2019",
      score: "44.40",
      icon: "📚",
    },
  ],
  certs: [
    { title: "Java Full Stack Developer", org: "Qspiders · 2026", icon: "☕", bg: "rgba(245,124,0,0.12)", col: "#fb923c" },
    { title: "MongoDB Node.js Developer Path", org: "MongoDB · Oct 2024", icon: "🍃", bg: "rgba(34,197,94,0.1)", col: "#4ade80" },
    { title: "Oracle Cloud Computing", org: "Oracle / EduVate · May 2024", icon: "☁️", bg: "rgba(59,126,255,0.12)", col: "#60a5fa" },
    { title: "Microsoft Office Fundamentals", org: "Microsoft · 2023", icon: "🪟", bg: "rgba(239,68,68,0.1)", col: "#f87171" },
    { title: "Research Publication — IJCRT", org: "\"AI Powered HR Recruitment\" · Apr 2025", icon: "📜", bg: "rgba(167,139,250,0.12)", col: "#a78bfa" },
    { title: "IoT & AI Internship Certificate", org: "Arul Technologies · 2023", icon: "🔌", bg: "rgba(34,211,238,0.1)", col: "#22d3ee" },
  ],
};

export default DATA;
